# ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

## Window current configuration
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_default_text " #W "
set -g @catppuccin_window_current_text " #W "

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-left-length 100
set -g status-right-length 100

set -g status-left ""
set -g status-right ""

set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_date_time}"

set -g status-interval 10
set -sg escape-time 10
set -g history-limit 100

run-shell "~/.config/tmux/plugins/tmux-cpu/cpu.tmux"

# Change prefix to Ctrl+a (more ergonomic)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Vim Options
set-window-option -g mode-keys vi

# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Update the default binding of 'Enter' to use copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# No prefix needed (-n flag)
bind -n C-t new-window

bind-key x kill-pane
