# Core settings
set -g mouse on
set -g default-terminal "tmux-256color"
set -g history-limit 100
set -g status-interval 10
set -sg escape-time 10
set-option -g focus-events on

# Remap prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Popup shell (scratchpad)
bind -n C-t display-popup \
  -x C -y C \
  -d "#{pane_current_path}" \
  -w 70% \
  -h 70% \
  -E "zsh"

bind-key p display-popup \
  -x C -y C \
  -d "#{pane_current_path}" \
  -w 70% \
  -h 70% \
  -E "nvim '+lua vim.schedule(function() require(\"vault\").toggle_todo() end)'"

# Kill pane shortcut
bind-key x kill-pane

# Copy mode (Vim style)
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key  -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# Catppuccin theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Window labels
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_default_text " #W "
set -g @catppuccin_window_current_text " #W "

# Load plugin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g popup-style "bg=default,fg=default"
set -g popup-border-style "fg=default,bg=default"

# Status bar
set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""
set -g status-right ""
set -ag  status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_date_time}"

# Plugins
run-shell "~/.config/tmux/plugins/tmux-cpu/cpu.tmux"
